import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { MapPin, Route, Calendar, Star, Users, Shield } from "lucide-react"

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
      {/* Header */}
      <header className="container mx-auto px-4 py-6">
        <nav className="flex justify-between items-center">
          <div className="flex items-center space-x-2">
            <MapPin className="h-8 w-8 text-indigo-600" />
            <h1 className="text-2xl font-bold text-gray-900">TripNect India</h1>
          </div>
          <Link href="/auth">
            <Button variant="outline">Sign In</Button>
          </Link>
        </nav>
      </header>

      {/* Hero Section */}
      <main className="container mx-auto px-4 py-16">
        <div className="text-center max-w-4xl mx-auto">
          <h2 className="text-5xl font-bold text-gray-900 mb-6">Plan Your Perfect Road Trip Across India</h2>
          <p className="text-xl text-gray-600 mb-8">
            Let AI create personalized itineraries for your Indian road adventures. Discover hidden gems, plan routes,
            and make memories that last a lifetime.
          </p>
          <Link href="/auth">
            <Button size="lg" className="bg-indigo-600 hover:bg-indigo-700 text-lg px-8 py-4">
              Plan Your Trip
            </Button>
          </Link>
        </div>

        {/* Features */}
        <div className="grid md:grid-cols-3 gap-8 mt-20">
          <Card className="text-center hover:shadow-lg transition-shadow">
            <CardContent className="p-6">
              <Route className="h-12 w-12 text-indigo-600 mx-auto mb-4" />
              <h3 className="text-xl font-semibold mb-2">AI-Powered Planning</h3>
              <p className="text-gray-600">
                Get personalized itineraries generated by advanced AI based on your preferences and interests
              </p>
            </CardContent>
          </Card>

          <Card className="text-center hover:shadow-lg transition-shadow">
            <CardContent className="p-6">
              <MapPin className="h-12 w-12 text-indigo-600 mx-auto mb-4" />
              <h3 className="text-xl font-semibold mb-2">Interactive Maps</h3>
              <p className="text-gray-600">
                Visualize your route with detailed maps, location markers, and real-time navigation
              </p>
            </CardContent>
          </Card>

          <Card className="text-center hover:shadow-lg transition-shadow">
            <CardContent className="p-6">
              <Calendar className="h-12 w-12 text-indigo-600 mx-auto mb-4" />
              <h3 className="text-xl font-semibold mb-2">Save & Share</h3>
              <p className="text-gray-600">Save your trips, access them anytime, and share with friends and family</p>
            </CardContent>
          </Card>
        </div>

        {/* Stats Section */}
        <div className="grid md:grid-cols-4 gap-8 mt-20 text-center">
          <div>
            <div className="text-3xl font-bold text-indigo-600 mb-2">10K+</div>
            <div className="text-gray-600">Happy Travelers</div>
          </div>
          <div>
            <div className="text-3xl font-bold text-indigo-600 mb-2">500+</div>
            <div className="text-gray-600">Destinations Covered</div>
          </div>
          <div>
            <div className="text-3xl font-bold text-indigo-600 mb-2">25K+</div>
            <div className="text-gray-600">Trips Planned</div>
          </div>
          <div>
            <div className="text-3xl font-bold text-indigo-600 mb-2">4.8★</div>
            <div className="text-gray-600">User Rating</div>
          </div>
        </div>

        {/* Why Choose Us */}
        <div className="mt-20">
          <h3 className="text-3xl font-bold text-center text-gray-900 mb-12">Why Choose TripNect India?</h3>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            <div className="flex items-start space-x-4">
              <Star className="h-8 w-8 text-yellow-500 flex-shrink-0 mt-1" />
              <div>
                <h4 className="font-semibold text-gray-900 mb-2">Expert Local Knowledge</h4>
                <p className="text-gray-600">
                  Our AI is trained on extensive local data to provide authentic Indian travel experiences
                </p>
              </div>
            </div>
            <div className="flex items-start space-x-4">
              <Users className="h-8 w-8 text-green-500 flex-shrink-0 mt-1" />
              <div>
                <h4 className="font-semibold text-gray-900 mb-2">Community Driven</h4>
                <p className="text-gray-600">
                  Recommendations from real travelers who&#39;ve explored India&#39;s diverse landscapes
                </p>
              </div>
            </div>
            <div className="flex items-start space-x-4">
              <Shield className="h-8 w-8 text-blue-500 flex-shrink-0 mt-1" />
              <div>
                <h4 className="font-semibold text-gray-900 mb-2">Safe & Reliable</h4>
                <p className="text-gray-600">
                  Trusted routes, verified accommodations, and 24/7 support for your peace of mind
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* CTA Section */}
        <div className="text-center mt-20">
          <h3 className="text-3xl font-bold text-gray-900 mb-4">Ready to Start Your Adventure?</h3>
          <p className="text-lg text-gray-600 mb-8">
            Join thousands of travelers who trust TripNect India for their road trip planning
          </p>
          <Link href="/auth">
            <Button size="lg" className="bg-indigo-600 hover:bg-indigo-700">
              Get Started Free
            </Button>
          </Link>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-12 mt-20">
        <div className="container mx-auto px-4">
          <div className="grid md:grid-cols-4 gap-8">
            <div>
              <div className="flex items-center space-x-2 mb-4">
                <MapPin className="h-6 w-6 text-indigo-400" />
                <span className="text-xl font-bold">TripNect India</span>
              </div>
              <p className="text-gray-400">Your AI-powered companion for unforgettable Indian road trips.</p>
            </div>
            <div>
              <h4 className="font-semibold mb-4">Features</h4>
              <ul className="space-y-2 text-gray-400">
                <li>AI Trip Planning</li>
                <li>Interactive Maps</li>
                <li>Route Optimization</li>
                <li>Local Recommendations</li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold mb-4">Destinations</h4>
              <ul className="space-y-2 text-gray-400">
                <li>Rajasthan</li>
                <li>Kerala</li>
                <li>Himachal Pradesh</li>
                <li>Goa</li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold mb-4">Support</h4>
              <ul className="space-y-2 text-gray-400">
                <li>Help Center</li>
                <li>Contact Us</li>
                <li>Privacy Policy</li>
                <li>Terms of Service</li>
              </ul>
            </div>
          </div>
          <div className="border-t border-gray-800 mt-8 pt-8 text-center text-gray-400">
            <p>&copy; 2024 TripNect India. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  )
}
